In [11]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('DataPreprocessing.csv')
data.head()

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes

In [3]:
# use X for matrice
# use x for array
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [5]:
# https://towardsdatascience.com/imputing-missing-values-using-the-simpleimputer-class-in-sklearn-99706afaff46
si = SimpleImputer(missing_values=np.nan, strategy='mean')
# در این بخش شروع به یادگیری میکند با استفاده از دستور زیر
si.fit(X[:, 1:])
# با استفاده از دستور زیر شروع به اعمال دستورالعمل میکند
X[:, 1:] = si.transform(X[:, 1:])

In [6]:
X

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, 76533.33333333333],
       ['India', 40.0, 69600.0],
       ['Brazil', 43.77777777777778, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

In [8]:
# با استفاده از دستور زیر کلمات هند و برزیل و... را اول به ترتیب حروف الفبا پیاده سازی میکند
# و سپس با عدد آهنا را لیبل گذاری میکند
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])
X

array([[1, 49.0, 86400.0],
       [0, 32.0, 57600.0],
       [2, 35.0, 64800.0],
       [0, 43.0, 73200.0],
       [2, 45.0, 76533.33333333333],
       [1, 40.0, 69600.0],
       [0, 43.77777777777778, 62400.0],
       [1, 53.0, 94800.0],
       [2, 55.0, 99600.0],
       [1, 42.0, 80400.0]], dtype=object)

In [10]:
# remainder='passthrough' or 'drop'
ct = ColumnTransformer([('Country', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)
X
# در اینجا ستون اول را تبدیل به سه ستون میکند که در این مورد با پارامتر 0 و 1 مشخص میکند که اگر
# کشور هند را داشتیم یعنی پارامتر اول و سوم را با 0 نشان میدهد و پارامتر دوم را با 1 مشخص میکند

array([[0.0, 1.0, 0.0, 49.0, 86400.0],
       [1.0, 0.0, 0.0, 32.0, 57600.0],
       [0.0, 0.0, 1.0, 35.0, 64800.0],
       [1.0, 0.0, 0.0, 43.0, 73200.0],
       [0.0, 0.0, 1.0, 45.0, 76533.33333333333],
       [0.0, 1.0, 0.0, 40.0, 69600.0],
       [1.0, 0.0, 0.0, 43.77777777777778, 62400.0],
       [0.0, 1.0, 0.0, 53.0, 94800.0],
       [0.0, 0.0, 1.0, 55.0, 99600.0],
       [0.0, 1.0, 0.0, 42.0, 80400.0]], dtype=object)

In [12]:
# from sklearn.preprocessing import StandardScaler
# عدد رو منهای میانگین ستون تقسیم بر انحراف استاندارد ستون میکرد و جای خود عدد قرار میداد
ss = StandardScaler()
X = ss.fit_transform(X)
X
# در نهایت ماتریسی به دست می آید که اماده است برای تزریق به الگوریتم داده کاوی

array([[-0.65465367,  1.22474487, -0.65465367,  0.75887436,  0.74947325],
       [ 1.52752523, -0.81649658, -0.65465367, -1.71150388, -1.43817841],
       [-0.65465367, -0.81649658,  1.52752523, -1.27555478, -0.89126549],
       [ 1.52752523, -0.81649658, -0.65465367, -0.11302384, -0.25320042],
       [-0.65465367, -0.81649658,  1.52752523,  0.17760889,  0.        ],
       [-0.65465367,  1.22474487, -0.65465367, -0.54897294, -0.52665688],
       [ 1.52752523, -0.81649658, -0.65465367,  0.        , -1.0735698 ],
       [-0.65465367,  1.22474487, -0.65465367,  1.34013983,  1.38753832],
       [-0.65465367, -0.81649658,  1.52752523,  1.63077256,  1.75214693],
       [-0.65465367,  1.22474487, -0.65465367, -0.25834021,  0.29371249]])